import { app, BrowserWindow, ipcMain, dialog, crashReporter } from 'electron';

// Start the crash reporter as early as possible — before `app` is ready —
// so native crashes during startup are captured. When `CRASH_REPORT_URL` is
// unset we pass an empty submit URL and set `uploadToServer: false`, which
// keeps the reporter wired in (local minidumps still written) without trying
// to POST anywhere.
crashReporter.start({
	productName: 'Metadata Editor',
	companyName: 'metadata-electron',
	submitURL: process.env.CRASH_REPORT_URL ?? '',
	uploadToServer: !!process.env.CRASH_REPORT_URL,
	ignoreSystemCrashHandler: false,
});

import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import { Wavedata, MirrorConfiguration, AgentStatus } from '../types';
import * as chokidar from 'chokidar';
import { CHANNELS } from '../ipc-api';
import { metadataService } from './services/MetadataService';
import { mirrorService } from './services/MirrorService';
import { initAutoUpdater } from './services/AutoUpdater';
import { WaveFile } from 'wavefile';
import { logger } from './logger';

const log = logger.child('MAIN');

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
	app.quit();
}

let mainWindow: BrowserWindow;
let fileWatcher: chokidar.FSWatcher | null = null;
let fileWatcherPath: string | null = null;
let fileWatcherLastEvent: Date | null = null;
let fileWatcherError: string | null = null;

// Path traversal protection: allowlisted roots populated by user-driven
// dialog selections and directory scans.
const allowedRoots: Set<string> = new Set();

// In-flight mirror operations that have been asked to cancel. The
// `mirrorFiles` handler passes an `isCancelled` closure to the service that
// checks this set; it is cleared in the handler's finally block.
const cancelledOps: Set<string> = new Set();

const MAX_AUDIO_FILE_BYTES = 2 * 1024 * 1024 * 1024; // 2GB

const addAllowedRoot = (rootPath: string): void => {
	if (!rootPath) return;
	allowedRoots.add(path.resolve(rootPath));
};

const assertPathUnderAllowedRoot = (p: string): void => {
	if (!p || typeof p !== 'string') {
		throw new Error('Path not under an allowed root: ' + p);
	}
	const resolved = path.resolve(p);
	for (const root of allowedRoots) {
		if (resolved === root || resolved.startsWith(root + path.sep)) {
			return;
		}
	}
	throw new Error('Path not under an allowed root: ' + p);
};

const collectWavFilesRecursively = async (
	dirPath: string,
	visited: Set<string> = new Set()
): Promise<string[]> => {
	const entries = await fs.promises.readdir(dirPath, { withFileTypes: true });
	const wavFiles: string[] = [];

	for (const entry of entries) {
		const entryPath = path.join(dirPath, entry.name);
		if (entry.isDirectory()) {
			try {
				const realSubdir = await fs.promises.realpath(entryPath);
				if (visited.has(realSubdir)) {
					continue;
				}
				visited.add(realSubdir);
				wavFiles.push(
					...(await collectWavFilesRecursively(entryPath, visited))
				);
			} catch (error) {
				log.warn(
					`Skipping subdirectory ${entryPath} due to error:`,
					error
				);
			}
			continue;
		}

		if (entry.isFile() && path.extname(entry.name).toLowerCase() === '.wav') {
			wavFiles.push(entryPath);
		}
	}

	return wavFiles.sort((left, right) => left.localeCompare(right));
};

const createWindow = () => {
	mainWindow = new BrowserWindow({
		height: 800,
		width: 1200,
		minHeight: 600,
		minWidth: 1000,
		frame: false, // custom chrome
		transparent: false, // fully opaque window
		hasShadow: true,
		backgroundColor: '#0b1420',
		titleBarStyle: 'hidden',
		roundedCorners: true,
		webPreferences: {
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
			nodeIntegration: false,
			contextIsolation: true,
			webSecurity: true,
		},
		acceptFirstMouse: true,
	});

	// Ensure native traffic lights are hidden when using custom chrome
	try {
		// macOS only
		(mainWindow as any).setWindowButtonVisibility?.(false);
	} catch (e) {
		// no-op
	}

	// Log preload errors for debugging
	mainWindow.webContents.on('preload-error', (event, preloadPath, error) => {
		log.error('Preload script error:', preloadPath, error);
	});

	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

	if (!app.isPackaged) {
		mainWindow.webContents.openDevTools();
	}
};

const getAgentStatusSnapshot = (): AgentStatus[] => {
	const watcherActive = Boolean(fileWatcher);
	const watcherStatus = (() => {
		if (fileWatcherError) {
			return `Error: ${fileWatcherError}`;
		}
		if (watcherActive && fileWatcherPath) {
			return `Watching ${fileWatcherPath}`;
		}
		return 'Idle';
	})();

	const statuses: AgentStatus[] = [
		{
			name: 'file-watcher',
			active: watcherActive,
			lastRun: fileWatcherLastEvent
				? fileWatcherLastEvent.toISOString()
				: undefined,
			status: watcherStatus,
			error: fileWatcherError ?? undefined,
		},
		{
			name: 'auto-save',
			active: false,
			status: 'Manual save only',
		},
	];

	return statuses;
};

const broadcastAgentStatuses = () => {
	if (!mainWindow || mainWindow.isDestroyed()) {
		return;
	}
	mainWindow.webContents.send(
		CHANNELS.onAgentStatusChange,
		getAgentStatusSnapshot()
	);
};

const startFileWatcher = async (targetPath: string | null): Promise<void> => {
	if (fileWatcher) {
		await fileWatcher.close();
		fileWatcher = null;
	}

	if (!targetPath) {
		fileWatcherPath = null;
		fileWatcherLastEvent = null;
		fileWatcherError = null;
		broadcastAgentStatuses();
		return;
	}

	fileWatcher = chokidar.watch(targetPath, {
		persistent: true,
		ignoreInitial: true,
	});

	fileWatcherPath = targetPath;
	fileWatcherLastEvent = null;
	fileWatcherError = null;
	broadcastAgentStatuses();

	fileWatcher.on('change', (changedPath: string) => {
		fileWatcherLastEvent = new Date();
		if (mainWindow && !mainWindow.isDestroyed()) {
			mainWindow.webContents.send(CHANNELS.onFileChanged, changedPath);
		}
		broadcastAgentStatuses();
	});

	fileWatcher.on('error', (error) => {
		log.error(`File watcher error: ${error}`);
		fileWatcherError = error instanceof Error ? error.message : String(error);
		broadcastAgentStatuses();
	});

	fileWatcher.on('ready', () => {
		broadcastAgentStatuses();
	});
};

app.on('ready', () => {
	initAutoUpdater();
	createWindow();
});

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
});

app.on('activate', () => {
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
});

// Window control IPC
ipcMain.handle(CHANNELS.windowMinimize, async () => {
	if (mainWindow && !mainWindow.isDestroyed()) {
		mainWindow.minimize();
	}
});

ipcMain.handle(CHANNELS.windowClose, async () => {
	if (mainWindow && !mainWindow.isDestroyed()) {
		mainWindow.close();
	}
});

ipcMain.handle(CHANNELS.windowToggleFullscreen, async () => {
	if (mainWindow && !mainWindow.isDestroyed()) {
		const next = !mainWindow.isFullScreen();
		mainWindow.setFullScreen(next);
	}
});

ipcMain.handle(CHANNELS.readMetadata, async (event, filePath: string) => {
	try {
		assertPathUnderAllowedRoot(filePath);
		return await metadataService.readMetadata(filePath);
	} catch (error) {
		log.error('readMetadata failed for:', filePath, error);
		throw error;
	}
});

ipcMain.handle(
	CHANNELS.writeMetadata,
	async (event, filePath: string, metadata: Wavedata) => {
		assertPathUnderAllowedRoot(filePath);
		return metadataService.writeMetadata(filePath, metadata);
	}
);

ipcMain.handle(CHANNELS.openFile, async () => {
	const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
		properties: ['openFile'],
		filters: [{ name: 'WAV Files', extensions: ['wav'] }],
	});
	if (canceled || filePaths.length === 0) {
		return null;
	}
	const selected = filePaths[0];
	addAllowedRoot(path.dirname(selected));
	return selected;
});

ipcMain.handle(CHANNELS.openDirectory, async () => {
	const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
		properties: ['openDirectory'],
	});
	if (canceled) {
		return { canceled: true, filePaths: [] };
	}
	for (const p of filePaths) {
		addAllowedRoot(p);
	}
	return { canceled: false, filePaths };
});

ipcMain.handle(CHANNELS.scanDirectory, async (event, dirPath: string) => {
	try {
		addAllowedRoot(dirPath);
		assertPathUnderAllowedRoot(dirPath);
		const wavFiles = await collectWavFilesRecursively(dirPath);

		const total = wavFiles.length;
		const wavedata: Wavedata[] = [];

		if (total === 0) {
			return wavedata;
		}

		for (let index = 0; index < wavFiles.length; index++) {
			const filePath = wavFiles[index];
			const fileName = path.basename(filePath);
			try {
				const metadata = await metadataService.readMetadata(filePath);
				wavedata.push(metadata);
				if (event.sender.isDestroyed()) {
					break;
				}
				event.sender.send(CHANNELS.onProgressUpdate, {
					fileName,
					processed: index + 1,
					total,
					percentage: Math.round(((index + 1) / total) * 100),
				});
			} catch (error) {
				log.error(`Failed to parse metadata for ${filePath}:`, error);
				if (event.sender.isDestroyed()) {
					break;
				}
				event.sender.send(CHANNELS.onProgressUpdate, {
					fileName,
					processed: index + 1,
					total,
					percentage: Math.round(((index + 1) / total) * 100),
					error: error instanceof Error ? error.message : String(error),
				});
			}
		}

		return wavedata;
	} catch (error) {
		log.error(`Failed to scan directory ${dirPath}:`, error);
		throw new Error(
			`Failed to scan directory "${dirPath}": ${error instanceof Error ? error.message : String(error)}`
		);
	}
});

ipcMain.handle(CHANNELS.loadAudioFile, async (event, filePath: string) => {
	try {
		assertPathUnderAllowedRoot(filePath);
		const stat = await fs.promises.stat(filePath);
		if (stat.size > MAX_AUDIO_FILE_BYTES) {
			throw new Error('File too large to preview');
		}
		const buffer = await fs.promises.readFile(filePath);
		const arrayBuffer = new Uint8Array(buffer).buffer;
		return arrayBuffer;
	} catch (error) {
		log.error(`Failed to load audio file ${filePath}:`, error);
		throw error;
	}
});

ipcMain.handle(CHANNELS.startFileWatching, async (event, filePath: string) => {
	if (!filePath) {
		await startFileWatcher(null);
		return;
	}
	addAllowedRoot(filePath);
	assertPathUnderAllowedRoot(filePath);
	await startFileWatcher(filePath);
});

ipcMain.handle(CHANNELS.stopFileWatching, async () => {
	await startFileWatcher(null);
});

app.on('before-quit', () => {
	if (fileWatcher) {
		void fileWatcher.close();
	}
});

// Global error handlers
process.on('uncaughtException', (error) => {
	log.error('Uncaught Exception:', error);
	// Don't exit for destroyed object errors during shutdown
	if (error.message && error.message.includes('Object has been destroyed')) {
		log.debug('Ignoring "Object has been destroyed" error during shutdown');
		return;
	}
	// For other critical errors, exit gracefully
	process.exit(1);
});

process.on('unhandledRejection', (reason, promise) => {
	log.error('Unhandled Rejection at:', promise, 'reason:', reason);
	// Don't crash for destroyed object errors
	if (
		reason &&
		typeof reason === 'object' &&
		'message' in reason &&
		typeof (reason as any).message === 'string' &&
		(reason as any).message.includes('Object has been destroyed')
	) {
		log.debug(
			'Ignoring "Object has been destroyed" rejection during shutdown'
		);
		return;
	}
});

ipcMain.handle(CHANNELS.checkIsDirectory, async (event, filePath: string) => {
	try {
		assertPathUnderAllowedRoot(filePath);
		const stats = await fs.promises.stat(filePath);
		return stats.isDirectory();
	} catch (error) {
		const code = (error as NodeJS.ErrnoException)?.code;
		if (code === 'ENOENT') return false; // File doesn't exist — not a directory
		log.error(`Failed to check if "${filePath}" is a directory:`, error);
		return false;
	}
});

ipcMain.handle(CHANNELS.createTestFiles, async () => {
	if (app.isPackaged) {
		throw new Error('Test file creation is only available in development');
	}
	const baseDir = await fs.promises.mkdtemp(
		path.join(os.tmpdir(), 'metadata-editor-')
	);

	const templates: Array<{
		filename: string;
		metadata: Partial<Wavedata>;
	}> = [
		{
			filename: 'SHOW1_Dialogue_Sc01A_01.wav',
			metadata: {
				show: 'SHOW1',
				category: 'Dialogue',
				subcategory: '01',
				scene: '01A',
				take: '01',
				slate: 'A',
				ixmlNote: 'First take',
				ixmlCircled: 'true',
				ixmlWildtrack: 'false',
			},
		},
		{
			filename: 'SHOW1_Music_Sc02_02.wav',
			metadata: {
				show: 'SHOW1',
				category: 'Music',
				subcategory: '02',
				scene: '02',
				take: '02',
				slate: '',
				ixmlNote: 'Background score',
				ixmlCircled: 'false',
				ixmlWildtrack: 'false',
			},
		},
		{
			filename: 'SHOW2_SFX_Sc10B_03.wav',
			metadata: {
				show: 'SHOW2',
				category: 'SFX',
				subcategory: '10',
				scene: '10B',
				take: '03',
				slate: 'B',
				ixmlNote: 'Explosion effect',
				ixmlCircled: 'false',
				ixmlWildtrack: 'true',
			},
		},
	];

	const createdFiles: string[] = [];
	const errors: Array<{ filePath: string; error: string }> = [];

	for (const template of templates) {
		const filePath = path.join(baseDir, template.filename);
		try {
			const wav = new WaveFile();
			const sampleRate = 48000;
			const durationSeconds = 2;
			const totalSamples = sampleRate * durationSeconds;
			const silence = new Array(totalSamples).fill(0);

			wav.fromScratch(1, sampleRate, '16', silence);
			const buffer = wav.toBuffer();
			await fs.promises.writeFile(filePath, buffer);

			const existing = await metadataService.readMetadata(filePath);
			const updated: Wavedata = {
				...existing,
				...template.metadata,
			};

			await metadataService.writeMetadata(filePath, updated);
			createdFiles.push(filePath);
		} catch (error) {
			const message = error instanceof Error ? error.message : String(error);
			errors.push({ filePath, error: message });
			log.error(`Failed to create test file ${filePath}:`, message);
		}
	}

	return {
		success: errors.length === 0,
		directory: baseDir,
		files: createdFiles,
		errors,
	};
});

ipcMain.handle(CHANNELS.getAgentStatuses, async () => {
	return getAgentStatusSnapshot();
});

ipcMain.handle(CHANNELS.toggleAgent, async (event, name, active) => {
	if (name === 'file-watcher') {
		if (!active) {
			await startFileWatcher(null);
			return;
		}

		if (fileWatcherPath) {
			await startFileWatcher(fileWatcherPath);
			return;
		}

		throw new Error('No file path available to start watcher');
	}

	throw new Error(`Unknown agent: ${name}`);
});

// Mirror Feature IPC Handlers
ipcMain.handle(CHANNELS.selectMirrorDestination, async () => {
	const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
		properties: ['openDirectory', 'createDirectory'],
		title: 'Select Mirror Destination Directory',
	});
	if (canceled || filePaths.length === 0) {
		return null;
	}
	addAllowedRoot(filePaths[0]);
	return filePaths[0];
});

ipcMain.handle(
	CHANNELS.mirrorFiles,
	async (
		event,
		config: MirrorConfiguration,
		files: Wavedata[],
		opId: string
	) => {
		if (!opId || typeof opId !== 'string') {
			throw new Error('mirrorFiles requires a non-empty opId');
		}
		try {
			return await mirrorService.mirrorFiles(config, files ?? [], () =>
				cancelledOps.has(opId)
			);
		} catch (error) {
			log.error('Mirror operation failed:', error);
			throw error;
		} finally {
			cancelledOps.delete(opId);
		}
	}
);

ipcMain.handle(CHANNELS.cancelMirror, async (_event, opId: string) => {
	if (opId && typeof opId === 'string') {
		cancelledOps.add(opId);
	}
});

ipcMain.handle(
	CHANNELS.checkFileConflicts,
	async (event, config: MirrorConfiguration, files: Wavedata[]) => {
		try {
			return await mirrorService.checkFileConflicts(config, files ?? []);
		} catch (error) {
			log.error('File conflicts check failed:', error);
			throw error;
		}
	}
);

ipcMain.handle(
	CHANNELS.debugLog,
	async (event, message: string, data?: unknown) => {
		log.debug(`[RENDERER-DEBUG] ${message}`, data ?? '');
	}
);
