import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import { Wavedata, MirrorConfiguration, AgentStatus } from '../types';
import * as chokidar from 'chokidar';
import { CHANNELS } from '../ipc-api';
import { metadataService } from './services/MetadataService';
import { filenameParser } from './services/FilenameParser';
import { mirrorService } from './services/MirrorService';
import { WaveFile } from 'wavefile';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
	app.quit();
}

let mainWindow: BrowserWindow;
let fileWatcher: chokidar.FSWatcher | null = null;
let fileWatcherPath: string | null = null;
let fileWatcherLastEvent: Date | null = null;
let fileWatcherError: string | null = null;

const createWindow = () => {
	console.log('[MAIN] Creating window...');
	console.log('[MAIN] Preload path:', MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY);
	console.log('[MAIN] Renderer path:', MAIN_WINDOW_WEBPACK_ENTRY);
	console.log(
		'[MAIN] Preload file exists:',
		fs.existsSync(MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY)
	);

	// Additional debugging
	try {
		const stats = fs.statSync(MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY);
		console.log('[MAIN] Preload file size:', stats.size, 'bytes');
	} catch (error) {
		console.error('[MAIN] Error checking preload file:', error);
	}

	mainWindow = new BrowserWindow({
		height: 800,
		width: 1200,
		minHeight: 600,
		minWidth: 1000,
		frame: false, // custom chrome
		transparent: false, // fully opaque window
		hasShadow: true,
		backgroundColor: '#0b1420',
		titleBarStyle: 'hidden',
		roundedCorners: true,
		webPreferences: {
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
			nodeIntegration: false,
			contextIsolation: true,
			webSecurity: true, // Re-enabled since IPC is working
		},
		acceptFirstMouse: true,
	});

	// Ensure native traffic lights are hidden when using custom chrome
	try {
		// macOS only
		(mainWindow as any).setWindowButtonVisibility?.(false);
	} catch (e) {
		// no-op
	}

	// Ensure no vibrancy is applied; we want an opaque window

	// Listen for console messages from the renderer process
	mainWindow.webContents.on(
		'console-message',
		(event, level, message, line, sourceId) => {
			const levelMap: Record<number, string> = {
				0: 'INFO',
				1: 'WARN',
				2: 'ERROR',
				3: 'DEBUG',
			};
			const logLevel = levelMap[level] || 'LOG';
			console.log(`[RENDERER-${logLevel}] ${message}`);
		}
	);

	// Listen for when the renderer is ready
	mainWindow.webContents.once('did-finish-load', () => {
		console.log('[MAIN] Renderer finished loading');
		// Check if preload worked by evaluating window.electronAPI
		mainWindow.webContents
			.executeJavaScript('!!window.electronAPI')
			.then((hasAPI) => {
				console.log('[MAIN] electronAPI available in renderer:', hasAPI);
			})
			.catch((err) => {
				console.error('[MAIN] Failed to check electronAPI:', err);
			});
	});

	// Listen for preload script errors
	mainWindow.webContents.on('preload-error', (event, preloadPath, error) => {
		console.error('[MAIN] Preload script error:', preloadPath, error);
	});

	// Listen for when DOM is ready
	mainWindow.webContents.once('dom-ready', () => {
		console.log('[MAIN] DOM ready');
	});

    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    if (!app.isPackaged) {
        mainWindow.webContents.openDevTools();
    }
};

const getAgentStatusSnapshot = (): AgentStatus[] => {
	const watcherActive = Boolean(fileWatcher);
	const watcherStatus = (() => {
		if (fileWatcherError) {
			return `Error: ${fileWatcherError}`;
		}
		if (watcherActive && fileWatcherPath) {
			return `Watching ${fileWatcherPath}`;
		}
		return 'Idle';
	})();

	const statuses: AgentStatus[] = [
		{
			name: 'file-watcher',
			active: watcherActive,
			lastRun: fileWatcherLastEvent ?? undefined,
			status: watcherStatus,
			error: fileWatcherError ?? undefined,
		},
		{
			name: 'auto-save',
			active: false,
			status: 'Manual save only',
		},
	];

	return statuses;
};

const broadcastAgentStatuses = () => {
	if (!mainWindow || mainWindow.isDestroyed()) {
		return;
	}
	mainWindow.webContents.send(
		CHANNELS.onAgentStatusChange,
		getAgentStatusSnapshot()
	);
};

const startFileWatcher = (targetPath: string | null) => {
	if (fileWatcher) {
		fileWatcher.close();
		fileWatcher = null;
	}

	if (!targetPath) {
		fileWatcherPath = null;
		fileWatcherLastEvent = null;
		fileWatcherError = null;
		broadcastAgentStatuses();
		return;
	}

	fileWatcher = chokidar.watch(targetPath, {
		persistent: true,
		ignoreInitial: true,
	});

	fileWatcherPath = targetPath;
	fileWatcherLastEvent = null;
	fileWatcherError = null;
	broadcastAgentStatuses();

	fileWatcher.on('change', (changedPath: string) => {
		fileWatcherLastEvent = new Date();
		if (mainWindow && !mainWindow.isDestroyed()) {
			mainWindow.webContents.send(CHANNELS.onFileChanged, changedPath);
		}
		broadcastAgentStatuses();
	});

	fileWatcher.on('error', (error) => {
		console.error(`File watcher error: ${error}`);
		fileWatcherError = error instanceof Error ? error.message : String(error);
		broadcastAgentStatuses();
	});

	fileWatcher.on('ready', () => {
		broadcastAgentStatuses();
	});
};

app.on('ready', () => {
	createWindow();
});

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
});

app.on('activate', () => {
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
});

// Window control IPC
ipcMain.handle(CHANNELS.windowMinimize, async () => {
	if (mainWindow && !mainWindow.isDestroyed()) {
		mainWindow.minimize();
	}
});

ipcMain.handle(CHANNELS.windowClose, async () => {
	if (mainWindow && !mainWindow.isDestroyed()) {
		mainWindow.close();
	}
});

ipcMain.handle(CHANNELS.windowToggleFullscreen, async () => {
	if (mainWindow && !mainWindow.isDestroyed()) {
		const next = !mainWindow.isFullScreen();
		mainWindow.setFullScreen(next);
	}
});

ipcMain.handle(CHANNELS.readMetadata, async (event, filePath: string) => {
	console.log('[MAIN] readMetadata called for:', filePath);
	try {
		const result = await metadataService.readMetadata(filePath);
		console.log('[MAIN] readMetadata successful for:', filePath);
		console.log('[MAIN] metadata result:', result);
		return result;
	} catch (error) {
		console.error('[MAIN] readMetadata failed for:', filePath, error);
		throw error;
	}
});

ipcMain.handle(
	CHANNELS.writeMetadata,
	async (event, filePath: string, metadata: Wavedata) => {
		return metadataService.writeMetadata(filePath, metadata);
	}
);

ipcMain.handle(CHANNELS.openFile, async () => {
	const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
		properties: ['openFile'],
		filters: [{ name: 'WAV Files', extensions: ['wav'] }],
	});
	if (canceled || filePaths.length === 0) {
		return null;
	}
	return filePaths[0];
});

ipcMain.handle(CHANNELS.openDirectory, async () => {
	const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
		properties: ['openDirectory'],
	});
	if (canceled) {
		return { canceled: true, filePaths: [] };
	}
	return { canceled: false, filePaths };
});

ipcMain.handle(CHANNELS.scanDirectory, async (event, dirPath: string) => {
	try {
		const files = await fs.promises.readdir(dirPath);
		const wavFiles = files
			.filter((file) => path.extname(file).toLowerCase() === '.wav')
			.map((file) => path.join(dirPath, file));

		const total = wavFiles.length;
		const wavedata: Wavedata[] = [];

		if (total === 0) {
			return wavedata;
		}

		for (let index = 0; index < wavFiles.length; index++) {
			const filePath = wavFiles[index];
			const fileName = path.basename(filePath);
			try {
				const metadata = await metadataService.readMetadata(filePath);
				wavedata.push(metadata);
				event.sender.send(CHANNELS.onProgressUpdate, {
					fileName,
					processed: index + 1,
					total,
					percentage: Math.round(((index + 1) / total) * 100),
				});
			} catch (error) {
				console.error(`Failed to parse metadata for ${filePath}:`, error);
				event.sender.send(CHANNELS.onProgressUpdate, {
					fileName,
					processed: index + 1,
					total,
					percentage: Math.round(((index + 1) / total) * 100),
					error: error instanceof Error ? error.message : String(error),
				});
			}
		}

		return wavedata;
	} catch (error) {
		console.error(`Failed to scan directory ${dirPath}:`, error);
		return []; // Return empty array on error
	}
});

ipcMain.handle(CHANNELS.loadAudioFile, async (event, filePath: string) => {
	try {
		console.log('[MAIN] Loading audio file:', filePath);
		const buffer = await fs.promises.readFile(filePath);
		console.log('[MAIN] Audio file loaded successfully, size:', buffer.length);
		const arrayBuffer = buffer.buffer.slice(
			buffer.byteOffset,
			buffer.byteOffset + buffer.byteLength
		);
		return arrayBuffer;
	} catch (error) {
		console.error(`Failed to load audio file ${filePath}:`, error);
		throw error;
	}
});

// Deprecated: file-watching handlers removed; use CHANNELS.* agents controls instead

app.on('before-quit', () => {
	if (fileWatcher) {
		fileWatcher.close();
	}
});

// Global error handlers
process.on('uncaughtException', (error) => {
	console.error('Uncaught Exception:', error);
	// Don't exit for destroyed object errors during shutdown
	if (error.message && error.message.includes('Object has been destroyed')) {
		console.log('Ignoring "Object has been destroyed" error during shutdown');
		return;
	}
	// For other critical errors, exit gracefully
	process.exit(1);
});

process.on('unhandledRejection', (reason, promise) => {
	console.error('Unhandled Rejection at:', promise, 'reason:', reason);
	// Don't crash for destroyed object errors
	if (
		reason &&
		typeof reason === 'object' &&
		'message' in reason &&
		typeof (reason as any).message === 'string' &&
		(reason as any).message.includes('Object has been destroyed')
	) {
		console.log(
			'Ignoring "Object has been destroyed" rejection during shutdown'
		);
		return;
	}
});

ipcMain.handle(CHANNELS.checkIsDirectory, async (event, filePath: string) => {
	try {
		const stats = await fs.promises.stat(filePath);
		return stats.isDirectory();
	} catch (error) {
		return false;
	}
});

ipcMain.handle(CHANNELS.createTestFiles, async () => {
	const baseDir = await fs.promises.mkdtemp(
		path.join(os.tmpdir(), 'metadata-editor-')
	);

	const templates: Array<{
		filename: string;
		metadata: Partial<Wavedata>;
	}> = [
		{
			filename: 'SHOW1_Dialogue_Sc01A_01.wav',
			metadata: {
				show: 'SHOW1',
				category: 'Dialogue',
				subcategory: '01',
				scene: '01A',
				take: '01',
				slate: 'A',
				ixmlNote: 'First take',
				ixmlCircled: 'true',
				ixmlWildtrack: 'false',
			},
		},
		{
			filename: 'SHOW1_Music_Sc02_02.wav',
			metadata: {
				show: 'SHOW1',
				category: 'Music',
				subcategory: '02',
				scene: '02',
				take: '02',
				slate: '',
				ixmlNote: 'Background score',
				ixmlCircled: 'false',
				ixmlWildtrack: 'false',
			},
		},
		{
			filename: 'SHOW2_SFX_Sc10B_03.wav',
			metadata: {
				show: 'SHOW2',
				category: 'SFX',
				subcategory: '10',
				scene: '10B',
				take: '03',
				slate: 'B',
				ixmlNote: 'Explosion effect',
				ixmlCircled: 'false',
				ixmlWildtrack: 'true',
			},
		},
	];

	const createdFiles: string[] = [];
	const errors: Array<{ filePath: string; error: string }> = [];

	for (const template of templates) {
		const filePath = path.join(baseDir, template.filename);
		try {
			const wav = new WaveFile();
			const sampleRate = 48000;
			const durationSeconds = 2;
			const totalSamples = sampleRate * durationSeconds;
			const silence = new Array(totalSamples).fill(0);

			wav.fromScratch(1, sampleRate, '16', silence);
			const buffer = wav.toBuffer();
			await fs.promises.writeFile(filePath, buffer);

			const existing = await metadataService.readMetadata(filePath);
			const updated: Wavedata = {
				...existing,
				...template.metadata,
			};

			await metadataService.writeMetadata(filePath, updated);
			createdFiles.push(filePath);
		} catch (error) {
			const message = error instanceof Error ? error.message : String(error);
			errors.push({ filePath, error: message });
			console.error(`Failed to create test file ${filePath}:`, message);
		}
	}

	return {
		success: errors.length === 0,
		directory: baseDir,
		files: createdFiles,
		errors,
	};
});

ipcMain.handle(CHANNELS.batchUpdateMetadata, async (event, updates) => {
	if (!Array.isArray(updates) || updates.length === 0) {
		return;
	}

	type UpdateEntry = {
		field: keyof Wavedata;
		value: unknown;
	};

	const groupedUpdates = updates.reduce((acc, update) => {
		if (!update || typeof update !== 'object') {
			return acc;
		}

		const { filePath, field, value } = update as {
			filePath: string;
			field: keyof Wavedata;
			value: unknown;
		};

		if (!filePath || typeof filePath !== 'string') {
			return acc;
		}

		const entry = acc.get(filePath) ?? [];
		entry.push({ field, value } as UpdateEntry);
		acc.set(filePath, entry);
		return acc;
	}, new Map<string, UpdateEntry[]>());

	const errors: string[] = [];

	for (const [filePath, fileUpdates] of groupedUpdates.entries()) {
		try {
			const metadata = await metadataService.readMetadata(filePath);
			const updatedMetadata: Wavedata = {
				...metadata,
				bwf: metadata.bwf ? { ...metadata.bwf } : undefined,
				iXML: metadata.iXML
					? JSON.parse(JSON.stringify(metadata.iXML))
					: undefined,
			};

			for (const { field, value } of fileUpdates) {
				if (!field) continue;

				switch (field) {
					case 'ixmlCircled':
					case 'ixmlWildtrack':
						(updatedMetadata as any)[field] =
							value === 'true' || value === true ? 'true' : 'false';
						break;
					case 'bwf':
					case 'iXML':
					case 'fileInfo':
					case 'duration':
					case 'fileSize':
						// Skip unsupported batch updates for complex fields
						console.warn(
							`Skipping batch update for unsupported field "${field}" on ${filePath}`
						);
						break;
					default:
						(updatedMetadata as any)[field] = value;
						break;
				}
			}

			await metadataService.writeMetadata(filePath, updatedMetadata);
		} catch (error) {
			const message = error instanceof Error ? error.message : String(error);
			errors.push(`${filePath}: ${message}`);
			console.error(`[MAIN] Failed batch update for ${filePath}:`, message);
		}
	}

	if (errors.length > 0) {
		throw new Error(
			`Failed to update metadata for ${errors.length} file(s): ${errors.join(
				'; '
			)}`
		);
	}
});

ipcMain.handle(
	CHANNELS.batchExtractMetadata,
	async (event, filePaths: string[]) => {
		console.log('[IPC] Received batchExtractMetadata request for:', filePaths);
		const results = filePaths.map((filePath) => {
			const filename = path.basename(filePath);
			const parsedData = filenameParser.parse(filename);
			if (parsedData) {
				return {
					...parsedData,
					filePath,
				};
			}
			return null;
		});
		const finalResults = results.filter((r) => r !== null);
		console.log('[IPC] Sending back extracted data:', finalResults);
		return finalResults;
	}
);

ipcMain.handle(CHANNELS.getAgentStatuses, async () => {
	return getAgentStatusSnapshot();
});

ipcMain.handle(CHANNELS.toggleAgent, async (event, name, active) => {
	if (name === 'file-watcher') {
		if (!active) {
			startFileWatcher(null);
			return;
		}

		if (fileWatcherPath) {
			startFileWatcher(fileWatcherPath);
			return;
		}

		throw new Error('No file path available to start watcher');
	}

	throw new Error(`Unknown agent: ${name}`);
});

ipcMain.handle(CHANNELS.triggerAgent, async (event, name) => {
	if (name === 'file-watcher') {
		if (fileWatcherPath) {
			startFileWatcher(fileWatcherPath);
			return;
		}
		throw new Error('No file path available to trigger watcher');
	}

	throw new Error(`Unknown agent: ${name}`);
});

// Mirror Feature IPC Handlers
ipcMain.handle(CHANNELS.selectMirrorDestination, async () => {
	const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
		properties: ['openDirectory', 'createDirectory'],
		title: 'Select Mirror Destination Directory',
	});
	if (canceled || filePaths.length === 0) {
		return null;
	}
	return filePaths[0];
});

// We need a way to pass the current files list to the mirror service
// Since we don't have global state in the main process, we'll need to pass it from renderer
let currentFiles: Wavedata[] = [];

ipcMain.handle(CHANNELS.setCurrentFiles, async (event, files: Wavedata[]) => {
	currentFiles = files;
	console.log('[MAIN] Current files updated, count:', files.length);
});

ipcMain.handle(
	CHANNELS.mirrorFiles,
	async (event, config: MirrorConfiguration) => {
		console.log('[MAIN] Mirror files requested with config:', config);
		try {
			const result = await mirrorService.mirrorFiles(config, currentFiles);
			console.log('[MAIN] Mirror operation completed:', result);
			return result;
		} catch (error) {
			console.error('[MAIN] Mirror operation failed:', error);
			throw error;
		}
	}
);

ipcMain.handle(
	CHANNELS.checkFileConflicts,
	async (event, config: MirrorConfiguration) => {
		console.log('[MAIN] Check file conflicts requested');
		try {
			const conflicts = await mirrorService.checkFileConflicts(
				config,
				currentFiles
			);
			console.log(
				'[MAIN] File conflicts check completed:',
				conflicts.length,
				'conflicts found'
			);
			return conflicts;
		} catch (error) {
			console.error('[MAIN] File conflicts check failed:', error);
			throw error;
		}
	}
);

// Debug helper to forward renderer logs to main console
ipcMain.handle(
	CHANNELS.debugLog,
	async (event, message: string, data?: any) => {
		console.log(
			`[RENDERER-DEBUG] ${message}`,
			data ? JSON.stringify(data, null, 2) : ''
		);
	}
);

// Progress and agent status will be updated when real operations occur
// No dummy periodic updates needed

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
